services:
  domain_web:
    build: .
    container_name: web
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - domain_db
    restart: always
  domain_db:
    image: postgres:17-alpine
    container_name: domain_db
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
  redis:
    image: redis:8-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
volumes:
  postgres_data:

